### ISSUE TITLE
WindowInteropHelper not visible

### ISSUE THREAD

**Issue by Xopoko** [riverar/sample-win10-aeroglass#2]
Where i can find this class? In windows 10 UWP i adding WindowsBase.dll and import System.Windows.Interop, but this class is still not visible.

**Comment by riverar** [comment]
This hasn't been tested in UWP apps and likely doesn't work.

**Comment by ConfusedHorse** [comment]
Have a look at this example of the acrylic look in an UWP application: [AcrylicControls.Example](https://github.com/ConfusedHorse/BlurryControls/tree/master/AcrylicControls.Example)
