### ISSUE TITLE
Changing Blur Strength

### ISSUE THREAD

**Issue by rondotdll** [riverar/sample-win10-aeroglass#5]
Maybe I am just missing something, but I don't see a way to change the strength of the blur? I would like to make it less blurry so the effect is more apparent

**Comment by rondotdll** [comment]
Seeing this now, I realize this thread is probably way dead but whatever

**Comment by riverar** [comment]
I don't believe you can control that from this DWM API.

**Comment by rondotdll** [comment]
OK thank you! Also, I'm noticing a huge performance drop when it comes to making the window draggable? Is there any fix you know of off the top of your head?

**Comment by riverar** [comment]
Sadly it's a Windows bug since 19H1 with no fix. Microsoft refuses to support it, (it broke their windows too) which makes the technique somewhat useless now.

**Comment by rondotdll** [comment]
Ahh, I see. What a shame it is that the decided to abandon such a cool feature. Thanks for you help anyways, Cheers!
